### ISSUE TITLE
Can't start the docker image

### ISSUE THREAD

**Issue by nmalcev** [KnowledgeCaptureAndDiscovery/wings#125]
**Describe the bug**
On the master branch, commands `docker-compose up -d --build` and `docker-compose up -d` don't starts the application server.
Log messages contain exceptions.

**To Reproduce**
Steps to reproduce the behavior (first case):
1. Run the command 'docker-compose up -d --build'
2. Find in the console:
```
Downloaded from central: https://repo.maven.apache.org/maven2/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar (363 kB at 657 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar (185 kB at 328 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar (284 kB at 500 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Wings 4.2.3:
[INFO] 
[INFO] Wings Core ......................................... SUCCESS [  0.011 s]
[INFO] Wings Planner ...................................... FAILURE [01:00 min]
[INFO] Wings Portal ....................................... SKIPPED
[INFO] Wings .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2021-03-24T16:40:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wings-planner: Could not resolve dependencies for project edu.isi.wings:wings-planner:jar:4.2.3: Could not find artifact edu.isi.kcap:ontapi:jar:1.1-SNAPSHOT in archiva.internal (https://www.wings-workflows.org/archiva/repository/internal/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wings-planner
The command '/bin/sh -c _JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn package' returned a non-zero code: 1
ERROR: Service 'wings' failed to build

```
Steps to reproduce the behavior (second case):
1. Run the command 'docker-compose up -d'
2. Run the command 'docker-compose logs'
3. Find in console:
```
wings_1  | 24-Mar-2021 16:41:20.251 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'debug' to '0' did not find a matching property.
wings_1  | 24-Mar-2021 16:41:20.431 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/wings-portal] has finished in [218] ms
wings_1  | 24-Mar-2021 16:41:20.433 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
wings_1  | 24-Mar-2021 16:41:20.443 SEVERE [main] org.apache.catalina.core.StandardService.startInternal Failed to start connector [Connector[AJP/1.3-8009]]
wings_1  | 	org.apache.catalina.LifecycleException: Protocol handler start failed
wings_1  | 		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1102)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.startup.Catalina.start(Catalina.java:688)
wings_1  | 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wings_1  | 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
wings_1  | 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
wings_1  | 		at java.lang.reflect.Method.invoke(Method.java:498)
wings_1  | 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
wings_1  | 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
wings_1  | 	Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
wings_1  | 		at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:274)
wings_1  | 		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1100)
wings_1  | 		... 12 more
wings_1  | 24-Mar-2021 16:41:20.444 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 267 ms
```
4. Run the command 'docker-compose ps'
5. Find in the console:
```
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                    NAMES
b2c3efd23ff4        kcapd/wings-base:latest   "catalina.sh run"   9 minutes ago       Up 9 minutes        0.0.0.0:8080->8080/tcp   wings_wings_1
```
6. Requests to http://localhost:8080/ returns message "HTTP Status 404 – Not Found"

**Expected behavior**
The application is available at the following link http://localhost:8080/

**Screenshots**
- [Screenshot 1](https://drive.google.com/file/d/1vFZ20e3LqAjy6VI0g02ideKEAzoGphhh/view?usp=sharing)
- [Screenshot 1](https://drive.google.com/file/d/1YiuQMogWoaW79r-XcyUITYAOydACCtvc/view?usp=sharing)
- [Screenshot 1](https://drive.google.com/file/d/10m-q80USgDqf_jlTa-2r7JyRcvO4RSA1/view?usp=sharing)

**Desktop:**
 - Linux  5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by varunratnakar** [comment]
Thank you for the bug report. Our internal maven repository was down which could have been causing issues. Please try again and let us know if you still experience issues.

**Comment by nmalcev** [comment]
@varunratnakar  Thank you for your response and for fixing the repository issue. But I still have such an exception:
```
wings_1  | 26-Mar-2021 09:53:05.306 SEVERE [main] org.apache.catalina.core.StandardService.startInternal Failed to start connector [Connector[AJP/1.3-8009]]
wings_1  | 	org.apache.catalina.LifecycleException: Protocol handler start failed
wings_1  | 		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1102)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
wings_1  | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
wings_1  | 		at org.apache.catalina.startup.Catalina.start(Catalina.java:688)
wings_1  | 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wings_1  | 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
wings_1  | 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
wings_1  | 		at java.lang.reflect.Method.invoke(Method.java:498)
wings_1  | 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
wings_1  | 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
wings_1  | 	Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
wings_1  | 		at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:274)
wings_1  | 		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1100)
wings_1  | 		... 12 more
wings_1  | 26-Mar-2021 09:53:05.306 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 359 ms
```

Then I updated wings-docker/config/tomcat/server.xml to avoid this exception:
``` XML
	<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" secretRequired="false"/>
```

And the compilation completes normally:
```
s$ docker-compose logs
Attaching to wings_wings_1
wings_1  | 26-Mar-2021 09:56:34.836 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.64
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 4 2021 23:14:16 UTC
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.64.0
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.8.0-44-generic
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
wings_1  | 26-Mar-2021 09:56:34.838 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_282-b08
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
wings_1  | 26-Mar-2021 09:56:34.839 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.26] using APR version [1.6.5].
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
wings_1  | 26-Mar-2021 09:56:34.840 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
wings_1  | 26-Mar-2021 09:56:34.845 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
wings_1  | 26-Mar-2021 09:56:34.912 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
wings_1  | 26-Mar-2021 09:56:34.922 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
wings_1  | 26-Mar-2021 09:56:34.934 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
wings_1  | 26-Mar-2021 09:56:34.935 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
wings_1  | 26-Mar-2021 09:56:34.937 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 520 ms
wings_1  | 26-Mar-2021 09:56:34.964 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
wings_1  | 26-Mar-2021 09:56:34.964 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.64
wings_1  | 26-Mar-2021 09:56:34.975 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/wings-portal]
wings_1  | 26-Mar-2021 09:56:35.008 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'debug' to '0' did not find a matching property.
wings_1  | 26-Mar-2021 09:56:35.188 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/wings-portal] has finished in [212] ms
wings_1  | 26-Mar-2021 09:56:35.190 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
wings_1  | 26-Mar-2021 09:56:35.195 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
wings_1  | 26-Mar-2021 09:56:35.197 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 260 ms

```

But requests to the web page http://localhost:8080/ still returns "HTTP Status 404-Not Found". Could you please tell me what is going wrong?

**Comment by IKCAP** [comment]
It should be working according to the logs. Please try to visit
http://localhost:8080/wings-portal

**Comment by nmalcev** [comment]
This URL also returns a 404 page.
![image](https://user-images.githubusercontent.com/665443/112620930-6b4ddb80-8e29-11eb-9664-da40ee770563.png)

**Comment by varunratnakar** [comment]
I've updated how the docker image was being created. Can you pull and try again ?

**Comment by nmalcev** [comment]
The app works, thank you!
